### ISSUE TITLE
Calls to v2 sources always are set as retries.

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [chocolatey/NuGet.Client#16]
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.

### What You Are Seeing?

When using `ListResource.ListAsync()` or `PackageSearchResource.SearchAsync()`, there is always a message about `Enhanced retry: HttpRetryHandler is in a state that retry would have been abandoned or not waited if it were not enabled.` before each http call to a v2 feed. This makes the call slower, as if it is set as a retry, there is an additional delay.

There is an upstream bug report here: https://github.com/NuGet/Home/issues/12195

### What is Expected?

That using `ListResource.ListAsync()` or `PackageSearchResource.SearchAsync()` does not use retry mode, unless a retry is actually needed.

### How Did You Get This To Happen?

Run `choco.exe search googlechrome --source=https://community.chocolatey.org/api/v2 --verbose` with v2.0.0 develop build

### System Details

* Operating System: Win 10
* Windows PowerShell version: 5.1
* Chocolatey CLI Version: 2.0.0 development build
* Chocolatey Licensed Extension version: N/A
* Chocolatey License type: N/A
* Terminal/Emulator: PowerShell

### Installed Packages

```bash
None
```

### Output Log

```bash
N/A
```

### Additional Context

As noted in the upstream bug report, this is caused by retry being set to true if there is no cache context passed in, and the search and list methods do not have a way to pass in a cache context. 

I tried adding overloads which allow passing in a cache context, but it was not able to make it work, as the cache files were not working correctly in this situation and failing with error messages about paths not being found.
https://github.com/TheCakeIsNaOH/NuGet.Client/tree/list-cache-context

I also tried setting the `IsRetry` to false, and that appeared to work, but I do not know if there may be repercussions in non happy path situations, like infinite or no retries. 
https://github.com/TheCakeIsNaOH/NuGet.Client/tree/no-retry

**Comment by gep13** [comment]
@TheCakeIsNaOH I dug into this a bit, and the problem is exactly as you described.  When no SourceCacheContext is provided, the HttpRetryHandler is immediately invoked, and as a result, each outgoing HttpRequest has a 1 second delay imposed on it.

When running something like `choco outdated` for say 100 packages, this operation is going to take at a minimum 100 seconds to complete, since there is an outgoing query for each package, and each one will have a 1 second delay imposed on it.

In order to make this work correctly, we have to be able to provide a `ChocolateySourceCacheContext` object to every query that make within the NuGet.Client.  For the most part, we should be able to provide this to the methods that we call directly, for example `PackageAsync`, however, in other places, we need to be able to pass one of these objects much earlier in the invocation of NuGet.Client assemblies, and significant changes will be required to allow this to happen.
